### ISSUE TITLE
Corrections

### ISSUE THREAD

**Issue by Freydal** [ParadigmFoundation/whitepaper#1]
* Table 2
  * maker:
    * This is not required. An order can be submitted from a poster with no signature.
    * For example the radar relay reaper just cross posts orders into our system.
  * posterSignature:
    * Not required for the library Order creation, but is required for OrderStream submission.  I'm not sure if that is necessary to call out here.
  * This structure is something we should definitely consider having another pass on.  Perhaps we can clean up the integrations between connect and subcontract argument specification.
* 3.2.2
  * Point 2 is currently not true. There has been a little discussion around the desire to continue with the proxy architecture.  This specification may be more true if we make changes to the currently very generic permission mechanism.
* 3.2.3
  * Voting -  The voting contract is more general and is blind to some aspects of the challenge.  It is also provides meaningful functionality for outside users.  The voting operation transactions go directly to this contract.  Resolution for challenge winnings in result of a vote do come directly from the validator registry.  Voting in the future will support other activities as well.
* 3.2.6
  * **system vs current** if the following issues regarding 'system balance' are more generically perhaps available balance would be less confusing.
  * 1 - b - iv: it is the treasury 'currentBalance' that must stay funded. The use of system balance may not refer to the 'systemBalance', but I wanted to clarify.
  * 1 - c: 'are automatically accepted' -> 'may be confirmed'
  * 2 - a : system vs current
  * 2 - c:  system balance is more appropriate here.  The tokens desired to be committed to the vote is a parameter with the upper bounds of the systemBalance
* A few places mention voters pay out due to their vote position, but it doesn't specify that they are getting proportional payout of the voter cut.  There is a parameterized split between the voters and stakeholder(listing/challenge).

**Comment by pasiphae00** [comment]
should all be addressed (forgot to close until now)
